import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
// import { Inter } from "next/font/google";
import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export const viewport: Viewport = {
  themeColor: "black",
  maximumScale: 1,
  initialScale: 1,
  minimumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body
          className={`mx-auto max-w-screen-2xl overflow-hidden bg-black text-white`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
